services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - api_node_modules:/app/node_modules

  frontend:
    build:
      context: ./app_admin
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./app_admin:/app
      - angular_node_modules:/app/node_modules

volumes:
  api_node_modules:
  angular_node_modules:
