/**
 * index.js
 *
 * API route for the Travlr application.
 *
 * Responsibilities:
 *   - Define API endpoints.
 *   - Map HTTP requests to controller functions.
 *   - Export the configured Express router.
 *
 * Dependencies:
 *   - express
 *   - ../controllers/trips
 *
 * Routes:
 *   - GET /trips -> tripsController.tripsList
 */

const express = require("express");
const router = express.Router();
const jwt = require('jsonwebtoken');

const tripsController = require("../controllers/trips");
const authController = require("../controllers/authentication")

// rate limiter imports
const { createRateLimiter } = require('../middleware/rateLimit');
const authLimiter = createRateLimiter(10, 60*1000);
const readLimiter = createRateLimiter(1000, 60*1000);
const writeLimiter = createRateLimiter(100, 60*1000);

// Method to authenticate our JWT
function authenticateJWT(req, res, next) {
  // console.log('In Middleware');
  const authHeader = req.headers['authorization'];
  // console.log('Auth Header: ' + authHeader);
  if(authHeader == null) {
    console.log('Auth Header Required but NOT PRESENT!');
    return res.sendStatus(401);
  }

  let headers = authHeader.split(' ');
  if(headers.length < 1) {
    console.log('Not enough tokens in Auth Header: ' +
    headers.length);
    return res.sendStatus(501);
  }

  const token = authHeader.split(' ')[1];
  // console.log('Token: ' + token);
  if(token == null) {
    console.log('Null Bearer Token');
    return res.sendStatus(401);
  }
  // console.log(process.env.JWT_SECRET);
  // console.log(jwt.decode(token));
  const verified = jwt.verify(token, process.env.JWT_SECRET, (err,
    verified) => {
      if(err) {
        return res.sendStatus(401).json('Token Validation Error!');
      }
      req.auth = verified; // Set the auth paramto the decoded object
      next(); // We need to continue or this will hang forever
  });
}

// route for register endpoint
router.route("/register").post(authLimiter, authController.register);

// route for login endpoint
router.route("/login").post(authLimiter, authController.login);

/**
 * Route: GET /trips
 *
 * Retrieve all trip records.
 *
 * Preconditions:
 *   - Router is mounted by the application.
 *   - tripsController.tripsList is available.
 *
 * Postconditions:
 *   - Request is forwarded to tripsList().
 *   - HTTP response is generated by the controller.
 */
router
    .route("/trips")
    .get(readLimiter, tripsController.tripsList)
    .post(authenticateJWT, writeLimiter, tripsController.tripsAddTrip);

/**
 * Route: GET /trips/:tripCode
 *
 * Retrieve a single trip.
 *
 * Preconditions:
 *   - Router is mounted by the application.
 *   - tripsController.tripsFindByCode is available.
 *
 * Postconditions:
 *   - Request is forwarded to tripsFindByCode().
 *   - HTTP response is generated by the controller.
 */
router
    .route("/trips/:tripCode")
    .get(readLimiter, tripsController.tripsFindByCode)
    .put(authenticateJWT, writeLimiter, tripsController.tripsUpdateTrip);

module.exports = router;
