/**
 * index.js
 *
 * API route for the Travlr application.
 *
 * Responsibilities:
 *   - Define API endpoints.
 *   - Map HTTP requests to controller functions.
 *   - Export the configured Express router.
 *
 * Dependencies:
 *   - express
 *   - ../controllers/trips
 *
 * Routes:
 *   - GET /trips -> tripsController.tripsList
 */

const express = require("express");
const router = express.Router();
const authenticateJWT = require('../middleware/authenticateJWT');

const tripsController = require("../controllers/trips");
const authController = require("../controllers/authentication")

// rate limiter imports
const { createRateLimiter } = require('../middleware/rateLimit');
const authLimiter = createRateLimiter(10, 60*1000);
const readLimiter = createRateLimiter(1000, 60*1000);
const writeLimiter = createRateLimiter(100, 60*1000);

// route for register endpoint
router.route("/register").post(authLimiter, authController.register);

// route for login endpoint
router.route("/login").post(authLimiter, authController.login);

/**
 * Route: GET /trips
 *
 * Retrieve all trip records.
 *
 * Preconditions:
 *   - Router is mounted by the application.
 *   - tripsController.tripsList is available.
 *
 * Postconditions:
 *   - Request is forwarded to tripsList().
 *   - HTTP response is generated by the controller.
 */
router
    .route("/trips")
    .get(readLimiter, tripsController.tripsList)
    .post(authenticateJWT, writeLimiter, tripsController.tripsAddTrip);

/**
 * Route: GET /trips/:tripCode
 *
 * Retrieve a single trip.
 *
 * Preconditions:
 *   - Router is mounted by the application.
 *   - tripsController.tripsFindByCode is available.
 *
 * Postconditions:
 *   - Request is forwarded to tripsFindByCode().
 *   - HTTP response is generated by the controller.
 */
router
    .route("/trips/:tripCode")
    .get(readLimiter, tripsController.tripsFindByCode)
    .put(authenticateJWT, writeLimiter, tripsController.tripsUpdateTrip);

module.exports = router;
