/**
 * index.js
 *
 * API route for the Travlr application.
 *
 * Responsibilities:
 *   - Define API endpoints.
 *   - Map HTTP requests to controller functions.
 *   - Export the configured Express router.
 *
 * Dependencies:
 *   - express
 *   - ../controllers/trips
 *
 * Routes:
 *   - GET /trips -> tripsController.tripsList
 */

const express = require("express");
const router = express.Router();

const tripsController = require("../controllers/trips");
const authController = require("../controllers/authentication.js")

router.route("/register").post(authController.register);
router.route("/login").post(authController.login);

/**
 * Route: GET /trips
 *
 * Retrieve all trip records.
 *
 * Preconditions:
 *   - Router is mounted by the application.
 *   - tripsController.tripsList is available.
 *
 * Postconditions:
 *   - Request is forwarded to tripsList().
 *   - HTTP response is generated by the controller.
 */
router
    .route("/trips")
    .get(tripsController.tripsList)
    .post(authenticateJWT, tripsController.tripsAddTrip);

/**
 * Route: GET /trips/:tripCode
 *
 * Retrieve a single trip.
 *
 * Preconditions:
 *   - Router is mounted by the application.
 *   - tripsController.tripsFindByCode is available.
 *
 * Postconditions:
 *   - Request is forwarded to tripsFindByCode().
 *   - HTTP response is generated by the controller.
 */
router
    .route("/trips/:tripCode")
    .get(tripsController.tripsFindByCode)
    .put(authenticateJWT, tripsController.tripsUpdateTrip);

module.exports = router;
