name: Docker CI

on:
  workflow_call:

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Build containers
        run: docker compose build


      - name: Start containers
        run: docker compose up -d


      - name: Show container status
        run: docker compose ps


      - name: Wait for API
        run: |
          for i in {1..30}; do
            if curl --fail http://127.0.0.1:3000/; then
              exit 0
            fi
            sleep 2
          done

          echo "API did not start"
          docker compose logs
          exit 1


      - name: Check Angular container
        run: |
          curl --fail http://127.0.0.1:4200/


      - name: Docker logs on failure
        if: failure()
        run: docker compose logs


      - name: Stop containers
        if: always()
        run: docker compose down
