name: Module 7 CI Entry Point

on:
  push:
    branches: [module7]
    paths-ignore:
      - 'README.md'

jobs:
  backend:
    uses: ./.github/workflows/backend.yml

  frontend:
    uses: ./.github/workflows/frontend.yml

  #docker:
  #  uses: ./.github/workflows/docker.yml
