name: Module 2 CI

on:
  push:
    branches:
      - module2
    paths-ignore:
      - README.md

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: |
          npm start &
          npx wait-on http://localhost:3000/health

      - run: curl -f http://localhost:3000/health
      - run: curl -f http://localhost:3000/
      - run: curl -f http://localhost:3000/travel
